# this is the name of continous deployment workflows in github actions.
name: Jam Lab Continous Deployment

#
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # install dependencies
      - name: Install Deps
        run: npm install

      - name: Build
        run: npm run build

      # Move build output to dist/jam-lab
      - name: Move build output from dist to dist/jam-lab
        run: |
          mkdir -p dist/jam-lab
          shopt -s extglob
          mv dist/!(jam-lab) dist/jam-lab

      # deploy project

      - name: Deploy to production url
        # if you have different requirements for deployment suppose your main brach for production and you have another branch for development then you can use this branch option to deploy your project to different branches.
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          # if uses: JamesIves/github-pages-deploy-action@4.1.4 runs it will automatically cerate new branch which name is gh-pages.
          branch: gh-pages
          folder: dist/jam-lab